name: Vulnerability Scan Failure Slack Notify
on:
  push: # todo: remove before merging
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 1' # 16:00 every Monday

jobs:
  vulnerability-scan-failure-notify:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-vulnerability-scan-failure-notify.yaml@ccm-UID2-4528-report-faillures-on-scheduled-vulnerability-detection-runs # todo: change to v3 before merging
    secrets: inherit
    with:
      vulnerability_severity: MEDIUM,HIGH,CRITICAL

